name: Gosub Continuous Integration (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install sqlite3 libsqlite3-dev libglib2.0-dev libcairo2-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libgtk-4-dev -y

      - name: Restore cargo cache
        id: restore-cargo-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Debug
        run: tree ~/.cargo
      - name: Build
        run: cargo build --verbose --all --workspace --all-features --locked
      - name: Clean
        run: |
          cargo install cargo-sweep --locked
          cargo sweep --installed
          cargo sweep --time 7
      - name: Save cargo cache
        uses: actions/cache/save@v4
        with:
          path: ~/.cargo/
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache/save@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-${{ github.sha }}
  test:
    needs: [build]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install sqlite3 libsqlite3-dev libglib2.0-dev libcairo2-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libgtk-4-dev -y
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Restore cargo cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache/restore@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-${{ github.sha }}
      - name: Debug
        run: tree ~/work/gosub-engine/
      - name: Run tests
        run: cargo test --verbose --all --no-fail-fast --all-features --all-targets --frozen

  clippy:
    needs: [build]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install sqlite3 libsqlite3-dev libglib2.0-dev libcairo2-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libgtk-4-dev -y
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Restore cargo cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache/restore@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-${{ github.sha }}
      - name: Run Clippy
        run: cargo clippy --all --tests --frozen -- -D warnings

  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run fmt
        run: cargo fmt --check --all
